version: "3.9"

services:
  amq-test-env:
    profiles:
      - dev
    image: amq-test-env
    # Privileged required to run as root and have the ability to open a pseudo terminal using socat
    privileged: true
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      target: dev
      ssh:
        - default
    volumes:
      - ./:/opt
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
